### ISSUE TITLE
Save file auto scrolls to top of page

### ISSUE THREAD

**Issue by tomwhite007** [RobertoMachorro/Moped#11]
Firstly, thanks for this app. As a previous Windows user, I need a simple notepad ...for notes (and plain text pasting to clear format stuff). This app is just right for that.

The one most annoying feature is in the title - I have to keep scrolling back down to my previous position in my file after using Command + S. Would be nice if I didn't have to.

**Comment by RobertoMachorro** [comment]
Thank you for using the app! This is an unfortunate side effect of the syntax highlight solution being used, other side effects: slow display, laggy scrolling on very long files, etc.

So, that is going to be replaced. It may take a few months, though.

**Comment by RobertoMachorro** [comment]
This issue has been addressed (#17), it has been public since version 1.8.3.
