### ISSUE TITLE
Lovely app - icon needs an update

### ISSUE THREAD

**Issue by rochakagrawal** [RobertoMachorro/Moped#13]
Lovely app - very fast and lightweight which is what i love

The scooter dock icon is good but now looks out of place with the other square icons on Big Sur

Would appreciate another icon or options. 

thanks

**Comment by RobertoMachorro** [comment]
Fully agree, will probably square up and add gradient. That may happen the Apple Silicon update.

<img width="268" alt="image" src="https://user-images.githubusercontent.com/7190436/99188504-60bc6080-272a-11eb-8ef8-4ebff75385a8.png">

**Comment by RobertoMachorro** [comment]
Initial Big Sure icon redesign.

<img width="720" alt="image" src="https://user-images.githubusercontent.com/7190436/99191551-59518300-273b-11eb-9943-8e84405a613a.png">

**Comment by RobertoMachorro** [comment]
Updated in 017611ec823197695115ab89da58c9af9958e52c , this will be included in the next release.

**Comment by rochakagrawal** [comment]
Wow love it.  When will the next update be pls ?

**Comment by RobertoMachorro** [comment]
This will be in 1-2 weeks, currently testing support for Apple Silicon (ARM/M1) support.

**Comment by rochakagrawal** [comment]
hi - there seems to be a big sur update that went live today - please see below. But the icon didn’t change on my MacBook. Anything i need to do?

thx

**Comment by RobertoMachorro** [comment]
Puzzling... I'll suggest deleting the App from Applications and downloading again from the App Store.

<img width="302" alt="image" src="https://user-images.githubusercontent.com/7190436/99908226-69271500-2caf-11eb-8fb7-ab3e7bd75994.png">

**Comment by rochakagrawal** [comment]
Thanks - quitting and restarting the app helped !!

**Comment by RobertoMachorro** [comment]
Fantastic! I should have asked if the app was closed during the update.
