### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by maksym-husiev** [RobertoMachorro/Moped#14]
It would be great to have tabs in application window. It will make possible to keep all opened files in the one window. Something like in Finder, for example

![image](https://user-images.githubusercontent.com/62958928/99554146-8ade7e80-29c7-11eb-9077-04d1c5b359de.png)

**Comment by RobertoMachorro** [comment]
Thanks for your feedback! This is already possible, but not on by default. If you got to View > Show Tab Bar, you will see the ability to add files in tabs. If you want to quickly merge all your separate windows, use Window > Merge All Windows.

<img width="672" alt="image" src="https://user-images.githubusercontent.com/7190436/99557258-79c64b00-2990-11eb-9baf-f24d097e51a5.png">

**Comment by maksym-husiev** [comment]
Oh! I missed this menu. Thx a lot. I just tried to use hotkeys (Cmd+T) to open new tab, but hotkeys no implemented yet, as I understand. 

I saw, you updated App icon, when you plan to upload this new version to App Store?

**Comment by RobertoMachorro** [comment]
Hotkey: good point!

Testing is being done for Apple Silicon ARM (M1) support. Once that completes, it will go to the App Store.

**Comment by maksym-husiev** [comment]
Good news! Waiting for updates. Thx a lot for your work!
