### ISSUE TITLE
Feature request: keyboard shortcut to make font larger / smaller

### ISSUE THREAD

**Issue by robinhuiser** [RobertoMachorro/Moped#16]
Moped is an awesome editor which I use during my screencast / Youtube videos to highlight bits of code.

The ability to quickly enlarge the font is very helpful.

**Comment by RobertoMachorro** [comment]
> Moped is an awesome editor which I use during my screencast / Youtube videos to highlight bits of code.

So cool! Thank you

> The ability to quickly enlarge the font is very helpful.

This is now in the work queue. The feature is to be implemented using the Command-Plus and Command-Minus key short cuts. Placing menu entries in the _Format_ menu or an upcoming _Editor_ menu. This matches behavior from Xcode.

**Comment by robinhuiser** [comment]
Awesome! Please let me know when the release is planned?

**Comment by RobertoMachorro** [comment]
Aprox 2 weeks from now, it will be in version 1.8.2 on the App Store.

**Comment by RobertoMachorro** [comment]
Feature completed  69a749a1b24d99460b091f570e5e565297155d07
