### ISSUE TITLE
loss of keyboard focus on Save

### ISSUE THREAD

**Issue by mepster** [RobertoMachorro/Moped#17]
Love Moped, just what I was looking for.

I have a small workflow bug: when you Save your document, the keyboard focus leaves the Moped window, and you have to click to get the focus back.

To reproduce:

- launch Moped
- save document - just pick the default filename.
- type a few characters, like "qwefqwef"
- Command-S to Save.
- try to type a few more characters - you can't. Instead you get the system warning beep.
- now if you click in the window to regain keyboard focus, then you can continue typing.

This just breaks the workflow of typing. Small thing but I just find it annoying when typing.

What I would like to happen at this point:
- you can just keep typing after a Save, without clicking in the window first.

Thanks! Otherwise Moped is a pleasure to use!

I tried looking at the code but I could not find where Command-S leads to model.data() (which I believe writes the file), and where the keyboard focus is lost. (I am advanced-beginner level MacOS programmer.)

**Comment by RobertoMachorro** [comment]
Thanks for giving Moped a try! It currently is using most of the default Document Based behavior that comes built-into macOS; this is why a lot of the actions are not in the code (like Save) - they are default behaviors of macOS itself.

The next step is to skip out of the default behaviors and use custom, that way the focus can be reverted back to the editor control. In addition, they source refreshes and auto-scrolls back to the top, which is annoying (see issue #11).

**Comment by RobertoMachorro** [comment]
This issue has been addressed (d0461c068d193128969060c0ec664746abf2ff83), it will be public on version 1.8.3.
