### ISSUE TITLE
I can barely see the cursor.

### ISSUE THREAD

**Issue by mikepetty21** [RobertoMachorro/Moped#19]
I can barely see the cursor which is located right after (string[] args). The file type is cs and the theme is vs.

<img width="713" alt="Moped Screen Shot" src="https://user-images.githubusercontent.com/610160/119866876-43432d00-beeb-11eb-956e-0a94897a80a6.png">

**Comment by RobertoMachorro** [comment]
Hi @mikepetty21 and thank you for your feedback!

Do you see this issue with this theme only?

Or is it with all themes?

What font size are you using?

**Comment by RobertoMachorro** [comment]
@mikepetty21 following up - I've been able to reproduce the issue: it's the theme (vs) that's the problem. If you switch to another theme, it'll work (such as _xcode_ or _androidstudio_ themes). I'll take a look at the theme itself soon.

![image](https://user-images.githubusercontent.com/7190436/120105593-91dd0b00-c127-11eb-9452-9f4c5fc5038a.png)

**Comment by mikepetty21** [comment]
I've noticed the same issue with the ascentic and tomorrow themes as well.

**Comment by RobertoMachorro** [comment]
An issue has been opened in Highlightr and will be fixed there.

**Comment by RobertoMachorro** [comment]
Fix is ready for the next release (1.6). This is a screenshot with the VS theme.

![image](https://user-images.githubusercontent.com/7190436/124370895-113f8c00-dc4a-11eb-9325-4032679e00db.png)
