### ISSUE TITLE
Feature Request: Arbitrary fonts (like monolisa.dev)

### ISSUE THREAD

**Issue by jlumbroso** [RobertoMachorro/Moped#20]
Currently the font options are limited. It would be nice to be able to select any installed font ([macOS has APIs to make this selection standard](https://developer.apple.com/documentation/appkit/nsfontpanel) that [would be nice to showcase](https://github.com/RobertoMachorro/Moped#manifesto---developers) 😇).

This would allow people to use excellent coding fonts like the free [Fira Code](https://github.com/tonsky/FiraCode), or the very deluxe [MonoLisa](https://www.monolisa.dev/).

![Screen Shot 2021-07-10 at 5 06 25 PM](https://user-images.githubusercontent.com/11770469/125176458-7d1d7980-e1a1-11eb-832a-b9c122e8f739.png)

**Comment by RobertoMachorro** [comment]
Definitely on the todo list now. Thanks for the suggestions!

**Comment by RobertoMachorro** [comment]
Implemented listing all system installed Monospaced (Fixed Pitch) fonts in Preferences for selection (7386a6890da0c9b4677ab9c6bdaf562b90515fd4).
This will be available in the next release.

<img width="908" alt="image" src="https://user-images.githubusercontent.com/7190436/125207483-80c10700-e25a-11eb-9396-b288fd6bd7e1.png">

**Comment by jlumbroso** [comment]
Simply amazing @RobertoMachorro!! — I also love that you found a solution that does not require an extra dialog (i.e., the [bad] font selection dialog). Filtering only monospace fonts is terrific IMHO, and it makes the list manageable for this list select.

This is really smart and well done! Thank you, thank you so much. 👏🏻

**Comment by jlumbroso** [comment]
@RobertoMachorro Just wanted to confirm it works like a charm!! 🥰

One thing I noticed is that if you have a document open, and you change the font, the opened document will not have the new font (but any document created or opened will). This may cause user confusion. If you would like to address this, here are two options:
1. Ensure the font change is live on existing windows (probably what the user expects, so they can try out several fonts in a row).
2. Or maybe have an alert when a font change is made (ideally only when an active window is opened) to say: "Just a heads-up: The font change will not be effective in your currently opened windows, but will be effective in any new document you open or create." (paraphrase)

Anyway, so, so happy I can use my cherished MonoLisa with Moped:
![Screen Shot 2021-07-11 at 6 07 12 PM](https://user-images.githubusercontent.com/11770469/125211278-35ffb900-e273-11eb-8c3c-ae2e9b004883.png)

**Comment by RobertoMachorro** [comment]
> One thing I noticed is that if you have a document open, and you change the font, the opened document will not have the new font (but any document created or opened will). This may cause user confusion.

I agree it may cause confusion. Currently, any change done in Preferences should update instantly on all windows, if that is not the case at your end, there may be a bug - see video below. I suggest closing all instances of Moped and trying again, sometimes if the app is open and you update, funny behavior exhibits.

https://user-images.githubusercontent.com/7190436/125213265-b0ced100-e27f-11eb-8c3f-f481b7d5db37.mov

> Anyway, so, so happy I can use my cherished MonoLisa with Moped:

Thanks for the kind words and the introduction to some fantastic fonts!
