### ISSUE TITLE
Add CLI shortcut to open Moped from Terminal

### ISSUE THREAD

**Issue by jlumbroso** [RobertoMachorro/Moped#23]
I like being able to open a file from the terminal, so I have created this global shortcut:
```bash
moped(){
   open -a "/Applications/Moped.app/Contents/MacOS/Moped" "$@"
}
```
in my `~/.zprofile` but there are other ways to solve this that don't require editing shell config, like creating a binary file `moped` putting it in `$PATH` and have it:
```bash
#!/bin/zsh
open -a "/Applications/Moped.app/Contents/MacOS/Moped" "$@"
```
assuming `Moped.app` is directly in `Applications`.

**Comment by RobertoMachorro** [comment]
Thanks for the tip! I have a similar script that iterates among all files in the command line, sometimes **open** eats up entries. See the bottom of the following blog:

https://roberto.machorro.net/projects/2019/08/25/moped-released-appstore.html

**Comment by RobertoMachorro** [comment]
Nothing further on this issue, closing.
