### ISSUE TITLE
Latest releases do not include precompiled binary

### ISSUE THREAD

**Issue by staceybellerose** [RobertoMachorro/Moped#26]
The README file is out-of-date, and links to the GitHub releases page for access to the latest precompiled binary. However, the last few releases do not include a binary. Please include a binary on GitHub when making new releases.

Reasoning: rather than using the Apple App Store to manage upgrades, I would prefer to use a [Homebrew](https://brew.sh/) cask and manage upgrades myself from the command line. If a precompiled binary is provided in the release, a cask can be created to download and install it.

**Comment by RobertoMachorro** [comment]
@staceybellerose thanks for the feedback! I love and use _Homebrew_ - will def make this happen.

**Comment by RobertoMachorro** [comment]
Added binary for release 1.8.2.

https://github.com/RobertoMachorro/Moped/releases/tag/v1.8.2
