### ISSUE TITLE
editor does not recognize c# files

### ISSUE THREAD

**Issue by rcolonel** [RobertoMachorro/Moped#29]
When Moped opening a *.cs file, the language is not recognized (under macOS Catalina).
![cs-file](https://user-images.githubusercontent.com/66009622/172368821-2921741d-f558-4ec1-85a7-8be437761858.png)

**Comment by rcolonel** [comment]
Thank you! CS-files are now recognized correctly!
And yet, please remove the version from the list of associated applications:

![Снимок экрана 2022-06-17 в 22 45 08 copy](https://user-images.githubusercontent.com/66009622/174284049-02c371c3-7b3c-466d-832f-f70bd0291f9d.png)

**Comment by danieltomasz** [comment]
The same for .md files (The file is recognized as plain text, not markdown)

**Comment by RobertoMachorro** [comment]
> Thank you! CS-files are now recognized correctly! And yet, please remove the version from the list of associated applications:
> 

Thank you for reporting the issue and verifying the fix.

With regards to the two entries of Moped in Finder, did you update the application via the App Store?

It's possible that you have two copies of it. To check for that, go to the menu options as follow:
🍏> _About this Mac_, when the **System Information** application comes up, click on **System Report...**, scroll down to _Applications_ and then look for Moped in applications. You will see something like this:

<img width="749" alt="image" src="https://user-images.githubusercontent.com/7190436/174406003-221d0e1b-f6e5-4803-9138-983c6bdc1f66.png">

Follow the path in _Location_ to the undesired copy and delete it.
