### ISSUE TITLE
BUG: Moped converts RTF file to "app from unidentified developer" without "saving" it.

### ISSUE THREAD

**Issue by AugustM** [RobertoMachorro/Moped#35]
As an experiment with Moped, I opened an RTF file, a text-based file, not a binary (if there is a binary RTF format). I can open this file in MacVim all day long without incident.

After quitting Moped, without saving the file or even attempting to make any changes, the file could not be opened with TextEdit. It produced the error:

>![image](https://github.com/RobertoMachorro/Moped/assets/4636183/5258df9e-2d0e-4aa9-a26c-d642c6613b87)
>"[K] Keyboard Maestro ⌥⌘K .rtf" cannot be opened because it is from an unidentified developer.
macOS cannot verify that this app is free from malware.
Moped created this file today at 7:08 PM.

When I clicked OK to the error message, then it could be opened normally. This should not have happened, I made no changes and did not save the file.

Why does the system report that the file was created by Moped when all it did was open it and not save it?

**Comment by RobertoMachorro** [comment]
A few questions:

1. Did you install Moped through the App Store or downloaded the binary from a website?
2. Was the RTF file downloaded from the web or locally created?
3. Could you send me the RTF's files extended attributes prior and after opening with Moped?

```
xattr -l path/to/file.rtf
```

Moped itself didn't change your file, the operating system (macOS) sometimes does. I'm suspecting that because Moped is Sandboxed, it is adding an extended attribute which is making something else freak out. This has been known to happen. I'm assuming that you downloaded MacVim from the web and gave full permissions to your drive?

Thanks!

**Comment by RobertoMachorro** [comment]
@AugustM One more thing, I don't want to rule out an auto-save from Moped (which would not be ok), so: Could you please check the time stamp before loading with Moped and then after? Do they differ? Thanks!

**Comment by AugustM** [comment]
Thanks for getting back to me, Roberto.

I'll be happy to try to recreate this issue, but it's going to be a few
days before I have time.

Regarding your previous questions:
1: I don't remember which version I have installed. I know I was looking
at both listings and often install from GitHub, if that's available, but I
don't know for sure. I did not build it with Xcode (although I would like
to be able to do that). Is there an easy way to tell whether I have the web
or AppStore version?

2. The RTF file was locally created.

3. Before and after extended attributes will wait until the same time I can
test the timestamp question.

Thanks for getting back to me so quickly and I hope to be able to provide
you with test results soon.

August

.

**Comment by AugustM** [comment]
Hi Roberto, here are some answers:

1. I installed Moped through the App Store.
2. The RTF was locally created. I have attached before and after copies of the file used in the following testing.
3. The output of `xattr -l` is pretty ungainly:

   ```text
   MohrBook-Pro-151202:DeskSpaceIDs amohr$ xattr -l *Research* > xttr_-l_output.txt
   MohrBook-Pro-151202:DeskSpaceIDs amohr$ wc xttr_-l_output.txt
     112447 2030718 8770023 xttr_-l_output.txt
   ```

   I suspect the huge size is that I used a screenshot for the file icon. Are there other options besides `-l` that I could use to get you the information you need? I'll attach the before and after versions anyway.

4. Here's the timestamp before opening it in Moped:

   ```text
   MohrBook:DeskSpaceIDs:$ ls -l *Research*
   -rw-r--r--@ 1 amohr  staff  4354 Nov 24 18:56 [R] Research ⌥⌘R  .rtf
   ```

   Here's the RTF file open in Moped:

   ![image-20240117201743442](/Users/amohr/Library/Application Support/typora-user-images/image-20240117201743442.png)

   And here's the timestamp after closing Moped:

   ```text
   MohrBook:DeskSpaceIDs:$ ls -l *Research*
   -rw-r--r--@ 1 amohr  staff  4354 Nov 24 18:56 [R] Research ⌥⌘R  .rtf
   ```

   No difference that I can see.

Here is what pops up when I attempt to open it again in my default app, DeskSpaceID.app, which is a straight clone of the public version of TextEdit v1.8.301.

![image-20240117202507112](/Users/amohr/Library/Application Support/typora-user-images/image-20240117202507112.png)

```text
macOS cannot verify the developer of "[R]
Research TR .rtf" Are you sure you want
to open it?
By opening this app, you will be overriding system
security which can expose your computer and
personal information to malware that may harm your
Mac or compromise yout privacy.
Moped created this file today at 8:13 PM.
```

Interestingly, while the timestamp on the file has not changed, the `xattr -l` output is different, off by a few bytes:

```text
MohrBook:DeskSpaceIDs:$ xattr -l *Research* > xttr_-l_output2.txt
MohrBook:DeskSpaceIDs:$ wc xttr_-l_output2.txt
112448 2030720 8770066 xttr_-l_output2.txt
MohrBook:DeskSpaceIDs:$ ls -l xttr*
-rw-r--r--@ 1 amohr  staff  8770023 Jan 17 23:11 xttr_-l_output.txt
-rw-r--r--@ 1 amohr  staff  8770066 Jan 18 00:26 xttr_-l_output2.txt
```

Given the small difference, I thought `diff` or some other file comparison tool might help. Here's what I  got  with `diff`:

```text
MohrBook-Pro-151202:DeskSpaceIDs amohr$ diff xttr*
112426c112426
< 00000000  AA 5E A8 65 00 00 00 00 0E AA A2 36 00 00 00 00  |.^.e.......6....|
---
> 00000000  54 E0 A8 65 00 00 00 00 F3 F0 03 11 00 00 00 00  |T..e............|
112447a112448
> com.apple.quarantine: 00e2;65a8cfec;Moped;
```

I'll attach the two RTF files and the two  `xattr` output files. GitHub doesn't support attaching RTF files,so I'll put all four in a Zip.

I hope this helps,

August

[MopedTestFiles.zip](https://github.com/RobertoMachorro/Moped/files/13974254/MopedTestFiles.zip)

**Comment by RobertoMachorro** [comment]
Thanks for sharing this and your thorough documentation of the issue. I've reached out to Apple, since I truly believe that this is an issue with macOS. I've experience the same with Shell scripts or any file that contains execute permissions. Will keep you posted.

**Comment by AugustM** [comment]
Thanks. Glad to help. I document thoroughly because it helps avoid the embarrassment of reporting my user error as a bug.  At first I found the difference in the before and after `xattr` output was that one was twice the size of the other. Wow. Turned out I'd made a backup and the `*` in my `xatter` command found the backup the second time but not the first, so the output was for two files, and I nearly reported that as a symptom. By making sure the report was actually clear enough for you to follow, I caught that.

**Comment by AugustM** [comment]
Thanks. At least there is a workaround in the sense that the error goes away after the first time you open the file. 

Unfortunately, I've been working on automating the opening of multiple Moped windows and having to allow for this error propagating to the *next* time I open a file, not with Moped, is an unhappy thought. Theoretically, Moped should only open TXT files and RTF files should only ever be opened by TextEdit or my DeskSpaceID.app. But user error happens so I'll have to be careful.

**Comment by RobertoMachorro** [comment]
_Note: Apple Case Follow-up: 792551585_

**Comment by AugustM** [comment]
My note above that the problem goes away after you open the file was a bit shortsighted. I had trouble even opening files, that is, switching to an already open file, via Keyboard Maestro, even though I could open the same file from the Moped Windows menu. I persistently got a slightly different "app from an unidentified developer" error:
```text
[Filename] cannot be opened because it is from an unidentified developer.
macOS cannot verify that this app is free from malware.
```
That error message did not allow me to open the file anyway, it only had an OK button to acknowledge the warning. (And again the error message is describing a .TXT file as being an app.)

What cleared the error for me was to have System Preferences > Security and Privacy open and then when I got the error message, click OK. The Security and Privacy window changed to include the report about the file in *that* window was an "Open Anyway" button. I clicked that and another window asked me to confirm that really wanted to open the file. When I clicked OK there, the file opened and I had no further problems with that file.

I had to do that for 31 open Moped files when I tried to access each of them with Keyboard Maestro. Fortunately that's done and does not appear to be reoccurring (until I add more files to this set, of course).

**Comment by RobertoMachorro** [comment]
v1.8.6 is now in review with a suggestion from Apple to fix the problem. Keeping this issue open until fixed.

**Comment by RobertoMachorro** [comment]
Update: Moped v1.8.6 hit the AppStore yesterday afternoon. Please give it a try, it should resolve the problem. At my end I can open up RTFs and even shell scripts without them being flagged for quarantine.

If this still doesn't work for you, please make sure you are using the latest macOS and try with a fresh file (not previously flagged for quarantine). If it still fails, there are few more things to try.

**Comment by AugustM** [comment]
Thanks, I'll give it a try this evening. As for "latest OS", my hardware only supports Catalina. I'll see how this version works.

**Comment by RobertoMachorro** [comment]
@AugustM any luck? are we good to close this issue?

**Comment by AugustM** [comment]
The new version seems to work fine on Catalina and I was not able to get it to fail, so we're good. Thanks for following up.
