### ISSUE TITLE
Feature Request: Basic AppleScript Functions

### ISSUE THREAD

**Issue by AugustM** [RobertoMachorro/Moped#37]
This simple AppleScript script:
```applescript
tell application "Moped"
	set doc to front document
end tell
```
produces this error:
```text
error "Moped got an error: Can’t get document 1." number -1728 from document 1
```

Unfortunately, this means I have to abandon my use of Moped. I love the fact that I can have multiple Moped windows on multiple Mission Control Desktops and Moped will reopen them all after a reboot and preserve which Desktop each window was in. I have been developing tools to keep track of projects on different desktops, but not being able to query the name of the file open in Moped on the current Desktop is a dealbreaker. I can't move forward without that basic function.

I've done some exploring of how to add AppleScript support to simple apps and built test apps in Xcode that respond to AppleScript. I would be willing to try to do that for Moped, but I haven't yet gotten the downloaded project to build. See [Issue #36](https://github.com/RobertoMachorro/Moped/issues/36). 

I'm self-taught so I'm often missing key concepts or terminology. Would someone be willing to mentor me in making this work? I'm not new at programming, I've built macro packages for Troff, VI, and TeX, converted Troff to PageMaker, added tools to Acrobat Pro using JavaScript, but Xcode has layers of assumptions that I haven't found documented yet because I'm too often going in circles.

**Comment by AugustM** [comment]
I spoke too soon. It seems access to the `document` provides access to the *content* that is open in the window. I also found out about the magic AppleScript concept of `application process`.

The following AppleScript script returns what I need:
```applescript
tell application "System Events" to tell application process "Moped" to tell window 1 to return name
```
I can use either `name` or `title` with Moped. It seems that's not the case with all apps. I have not found out the difference between those properties yet.

**Comment by RobertoMachorro** [comment]
Document based applications (such as Moped) allow multiple windows (one per document). The **name** of the application remains the same, but the **title** will change depending on the opened document (or _Untitled_ if it's a new document).

**Comment by AugustM** [comment]
I get the same values returned for `name` and `title`. When I run:
```applescript
tell application "System Events" to tell application process "Moped" to tell window 1 to return name
```
I get the same as when I say, "`... return title`".

When say  "`... return properties`" in Script Debugger I get this:
 
![image](https://github.com/RobertoMachorro/Moped/assets/4636183/612277ff-a7de-4c1b-9725-70e8fb1aa049)
As you can see, both `name` and `title` return the same string, which is the filename of the file that is open in the current Mission Control Desktop.
