### ISSUE TITLE
Period occasionally appears when adding spaces on a line

### ISSUE THREAD

**Issue by dsmith20688** [RobertoMachorro/Moped#39]
typed several lines
for example typed

j
k
l

went back to add characters after the k, typed several spaces, after typing a period appears immediately after the k but a period was never entered.

ended up with

j
k.
l

**Comment by RobertoMachorro** [comment]
When hitting the space-bar twice on macOS, it will automatically do a period for you. It is meant to speed text entry. This happens in all applications, not just Moped.

If you would like to disable the feature, follow the instructions here:
https://osxdaily.com/2019/03/27/disable-period-typing-shortcut-mac/
