### ISSUE TITLE
nim language syntax highlighting not working

### ISSUE THREAD

**Issue by btbytes** [RobertoMachorro/Moped#8]
When I open the `.nim` files in Moped, the syntax highlighting is not applied. I do see `com.textadept.nim-source` on the left bottom corner, but the highlighting remains at `vt2015`. I see that there is a `nimrod` langauge, and manually selecting it applies the correct syntax highlighting.

**Comment by RobertoMachorro** [comment]
Thanks for reporting this! This has been addressed now and will be available to you on the next release.

Source Fix Commit: 29255677acae2faf7dae06d78cf838a260db4c9a
